USE [master]
GO
/****** Object:  Database [OnlineshopDb]    Script Date: 12/16/2015 10:51:43 AM ******/
CREATE DATABASE [OnlineshopDb] ON  PRIMARY 
( NAME = N'OnlineshopDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\OnlineshopDb.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OnlineshopDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\OnlineshopDb_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [OnlineshopDb] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnlineshopDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OnlineshopDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OnlineshopDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OnlineshopDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OnlineshopDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OnlineshopDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [OnlineshopDb] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [OnlineshopDb] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [OnlineshopDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OnlineshopDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OnlineshopDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OnlineshopDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OnlineshopDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OnlineshopDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OnlineshopDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OnlineshopDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OnlineshopDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [OnlineshopDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OnlineshopDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OnlineshopDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OnlineshopDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OnlineshopDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OnlineshopDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OnlineshopDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OnlineshopDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OnlineshopDb] SET  MULTI_USER 
GO
ALTER DATABASE [OnlineshopDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OnlineshopDb] SET DB_CHAINING OFF 
GO
USE [OnlineshopDb]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 12/16/2015 10:51:43 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Users](
	[UsrNAme] [varchar](50) NULL,
	[UsrEmail] [varchar](50) NOT NULL,
	[UsrPassword] [varchar](50) NOT NULL,
	[AdminId] [int] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
USE [master]
GO
ALTER DATABASE [OnlineshopDb] SET  READ_WRITE 
GO
